image_config: &image_config
  IMAGE_NAME: c64libci
  IMAGE_TAG: 0.1.5
  LINUX_VERSION: DEBIAN_BUSTER

version: 2

jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: echo "Building ${IMAGE_NAME} ${IMAGE_TAG}..."
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
      # - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10


workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build
