image_config: &image_config
  IMAGE_NAME: c64libci
  LINUX_VERSION: DEBIAN_BUSTER

version: 2

jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout
      - run: echo "Building ${IMAGE_NAME} 0.0.0 ..."
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:0.0.0 .

  push:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout
      - run: echo "Publishing ${IMAGE_NAME} ${CIRCLE_TAG}..."
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:${CIRCLE_TAG} .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:${CIRCLE_TAG}


workflows:
  version: 2
  build:
    jobs:
      - build

  publish:
    jobs:
      - push:
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^([0-9]+)\.([0-9]+)\.([0-9]+).*$/
